### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by floresj** [ruheni/db-diff#4]
Hey! I was reading the [Integrate Prisma with Platformatic DB](https://oss.platformatic.dev/docs/guides/prisma) guide where I encountered this nifty lib. I'm having issues running the command. After installing it using,

```bash
npm i --save-dev @ruheni/db-diff
```

I continue to receive the following error:

```bash
npx db-diff

# Error output
TypeError
v is not a function
```

When I inspect the `dist/index.js` file, I noticed it's erroring out here despite me having the `@platformatic/service` dependency installed.

```node
#!/usr/bin/env node
import d from 'chalk';
import { execaCommand } from 'execa';
import a from 'fs/promises';
import { Command } from 'commander';
import v from '@platformatic/service';   // <-------------- Errors out here
import u from 'path';
```

Is there something else I need to execute in order to be able to run this utility?

Here's my setup

```bash
npm --version
9.5.1
node --version
v18.16.0
npx platformatic --version
v0.22.0
```

Thanks!

**Comment by ruheni** [comment]
Hey 👋

Thanks for raising this. I can confirm I can reproduce this. I'll look at this and push a fix in the next few days. 🙂

**Comment by ruheni** [comment]
Hey 👋

Quick follow-up, I've published a release that should fix the error. Let me know if it works for you. 🙂

**Comment by floresj** [comment]
Hey @ruheni ! Whooohoooo. Thanks so much. It's working now!

<img width="355" alt="image" src="https://github.com/ruheni/db-diff/assets/5938731/fd5c023f-07ef-4251-bac2-72972bc00b2b">
